name: publish-documentation

on:
  push:
    branches:
      - main
      - tidy-branch
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false # Do not checkout large submodules for documentation builds

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build and Deploy Documentation
        run: |
          mkdocs gh-deploy --force
